#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataConn
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db47a34fa5f3d14e7291c1a77201706c4e")]
	public partial class countryDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public countryDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db47a34fa5f3d14e7291c1a77201706c4eConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public countryDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public countryDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public countryDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public countryDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Country> Countries
		{
			get
			{
				return this.GetTable<Country>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GET_COUNTRIES")]
		public ISingleResult<GET_COUNTRIESResult> GET_COUNTRIES([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string pName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string pAlpha2Code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(20)")] string pAlpha3Code, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string pNativeName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string pRegion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string pSubRegion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> pAreaFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="BigInt")] System.Nullable<long> pAreaTo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pNumericCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string pNativeLanguage, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string pCurrencyCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(150)")] string pCurrencyName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pPage, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> pLimit)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pName, pAlpha2Code, pAlpha3Code, pNativeName, pRegion, pSubRegion, pAreaFrom, pAreaTo, pNumericCode, pNativeLanguage, pCurrencyCode, pCurrencyName, pPage, pLimit);
			return ((ISingleResult<GET_COUNTRIESResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Country")]
	public partial class Country
	{
		
		private string _name;
		
		private string _alpha2Code;
		
		private string _alpha3Code;
		
		private string _nativeName;
		
		private string _region;
		
		private string _subRegion;
		
		private string _latitude;
		
		private string _longitude;
		
		private System.Nullable<long> _area;
		
		private System.Nullable<int> _numericCode;
		
		private string _nativeLanguage;
		
		private string _currencyCode;
		
		private string _currencyName;
		
		private string _currencySymbol;
		
		private string _flag;
		
		public Country()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(200)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alpha2Code", DbType="NVarChar(20)")]
		public string alpha2Code
		{
			get
			{
				return this._alpha2Code;
			}
			set
			{
				if ((this._alpha2Code != value))
				{
					this._alpha2Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alpha3Code", DbType="NVarChar(20)")]
		public string alpha3Code
		{
			get
			{
				return this._alpha3Code;
			}
			set
			{
				if ((this._alpha3Code != value))
				{
					this._alpha3Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nativeName", DbType="NVarChar(200)")]
		public string nativeName
		{
			get
			{
				return this._nativeName;
			}
			set
			{
				if ((this._nativeName != value))
				{
					this._nativeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(100)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this._region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subRegion", DbType="NVarChar(200)")]
		public string subRegion
		{
			get
			{
				return this._subRegion;
			}
			set
			{
				if ((this._subRegion != value))
				{
					this._subRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="NVarChar(200)")]
		public string latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this._latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="NVarChar(200)")]
		public string longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this._longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="BigInt")]
		public System.Nullable<long> area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this._area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numericCode", DbType="Int")]
		public System.Nullable<int> numericCode
		{
			get
			{
				return this._numericCode;
			}
			set
			{
				if ((this._numericCode != value))
				{
					this._numericCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nativeLanguage", DbType="NVarChar(200)")]
		public string nativeLanguage
		{
			get
			{
				return this._nativeLanguage;
			}
			set
			{
				if ((this._nativeLanguage != value))
				{
					this._nativeLanguage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencyCode", DbType="NVarChar(100)")]
		public string currencyCode
		{
			get
			{
				return this._currencyCode;
			}
			set
			{
				if ((this._currencyCode != value))
				{
					this._currencyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencyName", DbType="NVarChar(150)")]
		public string currencyName
		{
			get
			{
				return this._currencyName;
			}
			set
			{
				if ((this._currencyName != value))
				{
					this._currencyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencySymbol", DbType="NVarChar(50)")]
		public string currencySymbol
		{
			get
			{
				return this._currencySymbol;
			}
			set
			{
				if ((this._currencySymbol != value))
				{
					this._currencySymbol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag", DbType="NVarChar(500)")]
		public string flag
		{
			get
			{
				return this._flag;
			}
			set
			{
				if ((this._flag != value))
				{
					this._flag = value;
				}
			}
		}
	}
	
	public partial class GET_COUNTRIESResult
	{
		
		private string _name;
		
		private string _alpha2Code;
		
		private string _alpha3Code;
		
		private string _nativeName;
		
		private string _region;
		
		private string _subRegion;
		
		private string _latitude;
		
		private string _longitude;
		
		private System.Nullable<long> _area;
		
		private System.Nullable<int> _numericCode;
		
		private string _nativeLanguage;
		
		private string _currencyCode;
		
		private string _currencyName;
		
		private string _currencySymbol;
		
		private string _flag;
		
		public GET_COUNTRIESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(200)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alpha2Code", DbType="NVarChar(20)")]
		public string alpha2Code
		{
			get
			{
				return this._alpha2Code;
			}
			set
			{
				if ((this._alpha2Code != value))
				{
					this._alpha2Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alpha3Code", DbType="NVarChar(20)")]
		public string alpha3Code
		{
			get
			{
				return this._alpha3Code;
			}
			set
			{
				if ((this._alpha3Code != value))
				{
					this._alpha3Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nativeName", DbType="NVarChar(200)")]
		public string nativeName
		{
			get
			{
				return this._nativeName;
			}
			set
			{
				if ((this._nativeName != value))
				{
					this._nativeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_region", DbType="NVarChar(100)")]
		public string region
		{
			get
			{
				return this._region;
			}
			set
			{
				if ((this._region != value))
				{
					this._region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subRegion", DbType="NVarChar(200)")]
		public string subRegion
		{
			get
			{
				return this._subRegion;
			}
			set
			{
				if ((this._subRegion != value))
				{
					this._subRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_latitude", DbType="NVarChar(200)")]
		public string latitude
		{
			get
			{
				return this._latitude;
			}
			set
			{
				if ((this._latitude != value))
				{
					this._latitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longitude", DbType="NVarChar(200)")]
		public string longitude
		{
			get
			{
				return this._longitude;
			}
			set
			{
				if ((this._longitude != value))
				{
					this._longitude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="BigInt")]
		public System.Nullable<long> area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this._area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_numericCode", DbType="Int")]
		public System.Nullable<int> numericCode
		{
			get
			{
				return this._numericCode;
			}
			set
			{
				if ((this._numericCode != value))
				{
					this._numericCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nativeLanguage", DbType="NVarChar(200)")]
		public string nativeLanguage
		{
			get
			{
				return this._nativeLanguage;
			}
			set
			{
				if ((this._nativeLanguage != value))
				{
					this._nativeLanguage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencyCode", DbType="NVarChar(100)")]
		public string currencyCode
		{
			get
			{
				return this._currencyCode;
			}
			set
			{
				if ((this._currencyCode != value))
				{
					this._currencyCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencyName", DbType="NVarChar(150)")]
		public string currencyName
		{
			get
			{
				return this._currencyName;
			}
			set
			{
				if ((this._currencyName != value))
				{
					this._currencyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_currencySymbol", DbType="NVarChar(50)")]
		public string currencySymbol
		{
			get
			{
				return this._currencySymbol;
			}
			set
			{
				if ((this._currencySymbol != value))
				{
					this._currencySymbol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flag", DbType="NVarChar(500)")]
		public string flag
		{
			get
			{
				return this._flag;
			}
			set
			{
				if ((this._flag != value))
				{
					this._flag = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
